((python-mode . ((pyvenv-activate . "~/prog/games/tdp/.venv")))
 (scss-mode . ((css-indent-offset . 2)))
 (web-mode . ((web-mode-markup-indent-offset . 2)
              (web-mode-code-indent-offset . 2)
              (web-mode-css-indent-offset . 2))))
